/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tuhuynh;

import com.google.gson.Gson;
import com.jinyframework.HttpServer;
import com.jinyframework.core.RequestBinderBase.HttpResponse;
import com.tuhuynh.handlers.BookHandler;
import lombok.val;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        val gson = new Gson();
        val server = HttpServer.port(1234)
                .useTransformer(gson::toJson);
        server.get("/", ctx -> HttpResponse.of("Hello World"));
        server.get("/books", BookHandler::listBook);
        server.get("/books/:id", BookHandler::getBook);
        server.post("/books", BookHandler::createBook);
        server.put("/books/:id", BookHandler::updateBook);
        server.delete("/books/:id", BookHandler::deleteBook);
        server.start();
    }
}
